package com.almacen.model;
// Generated 27/06/2016 04:27:58 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Articulo generated by hbm2java
 */
public class Articulo  implements java.io.Serializable {


     private Integer idArticulo;
     private Acceso acceso;
     private Marca marca;
     private SubCatalogoBienes subCatalogoBienes;
     private String articulo;
     private String cb;
     private String modelo;
     private String ubicacionFisica;
     private BigDecimal minimo;
     private BigDecimal maximo;
     private String esConsumible;
     private String caracteristicas;
     private String observaciones;
     private String foto;
     private Date fechaCaducidad;
     private Date fechaReg;
     private Set<ArticuloEntrada> articuloEntradas = new HashSet<ArticuloEntrada>(0);

    public Articulo() {
    }

	
    public Articulo(Acceso acceso, Marca marca, SubCatalogoBienes subCatalogoBienes, String articulo, Date fechaReg) {
        this.acceso = acceso;
        this.marca = marca;
        this.subCatalogoBienes = subCatalogoBienes;
        this.articulo = articulo;
        this.fechaReg = fechaReg;
    }
    public Articulo(Acceso acceso, Marca marca, SubCatalogoBienes subCatalogoBienes, String articulo, String cb, String modelo, String ubicacionFisica, BigDecimal minimo, BigDecimal maximo, String esConsumible, String caracteristicas, String observaciones, String foto, Date fechaCaducidad, Date fechaReg, Set<ArticuloEntrada> articuloEntradas) {
       this.acceso = acceso;
       this.marca = marca;
       this.subCatalogoBienes = subCatalogoBienes;
       this.articulo = articulo;
       this.cb = cb;
       this.modelo = modelo;
       this.ubicacionFisica = ubicacionFisica;
       this.minimo = minimo;
       this.maximo = maximo;
       this.esConsumible = esConsumible;
       this.caracteristicas = caracteristicas;
       this.observaciones = observaciones;
       this.foto = foto;
       this.fechaCaducidad = fechaCaducidad;
       this.fechaReg = fechaReg;
       this.articuloEntradas = articuloEntradas;
    }
   
    public Integer getIdArticulo() {
        return this.idArticulo;
    }
    
    public void setIdArticulo(Integer idArticulo) {
        this.idArticulo = idArticulo;
    }
    public Acceso getAcceso() {
        return this.acceso;
    }
    
    public void setAcceso(Acceso acceso) {
        this.acceso = acceso;
    }
    public Marca getMarca() {
        return this.marca;
    }
    
    public void setMarca(Marca marca) {
        this.marca = marca;
    }
    public SubCatalogoBienes getSubCatalogoBienes() {
        return this.subCatalogoBienes;
    }
    
    public void setSubCatalogoBienes(SubCatalogoBienes subCatalogoBienes) {
        this.subCatalogoBienes = subCatalogoBienes;
    }
    public String getArticulo() {
        return this.articulo;
    }
    
    public void setArticulo(String articulo) {
        this.articulo = articulo;
    }
    public String getCb() {
        return this.cb;
    }
    
    public void setCb(String cb) {
        this.cb = cb;
    }
    public String getModelo() {
        return this.modelo;
    }
    
    public void setModelo(String modelo) {
        this.modelo = modelo;
    }
    public String getUbicacionFisica() {
        return this.ubicacionFisica;
    }
    
    public void setUbicacionFisica(String ubicacionFisica) {
        this.ubicacionFisica = ubicacionFisica;
    }
    public BigDecimal getMinimo() {
        return this.minimo;
    }
    
    public void setMinimo(BigDecimal minimo) {
        this.minimo = minimo;
    }
    public BigDecimal getMaximo() {
        return this.maximo;
    }
    
    public void setMaximo(BigDecimal maximo) {
        this.maximo = maximo;
    }
    public String getEsConsumible() {
        return this.esConsumible;
    }
    
    public void setEsConsumible(String esConsumible) {
        this.esConsumible = esConsumible;
    }
    public String getCaracteristicas() {
        return this.caracteristicas;
    }
    
    public void setCaracteristicas(String caracteristicas) {
        this.caracteristicas = caracteristicas;
    }
    public String getObservaciones() {
        return this.observaciones;
    }
    
    public void setObservaciones(String observaciones) {
        this.observaciones = observaciones;
    }
    public String getFoto() {
        return this.foto;
    }
    
    public void setFoto(String foto) {
        this.foto = foto;
    }
    public Date getFechaCaducidad() {
        return this.fechaCaducidad;
    }
    
    public void setFechaCaducidad(Date fechaCaducidad) {
        this.fechaCaducidad = fechaCaducidad;
    }
    public Date getFechaReg() {
        return this.fechaReg;
    }
    
    public void setFechaReg(Date fechaReg) {
        this.fechaReg = fechaReg;
    }
    public Set<ArticuloEntrada> getArticuloEntradas() {
        return this.articuloEntradas;
    }
    
    public void setArticuloEntradas(Set<ArticuloEntrada> articuloEntradas) {
        this.articuloEntradas = articuloEntradas;
    }




}


