package com.almacen.model;
// Generated 29/06/2016 01:34:56 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * ArticuloSalida generated by hbm2java
 */
public class ArticuloSalida  implements java.io.Serializable {


     private Integer idArticuloSalida;
     private Acceso acceso;
     private ArticuloEntrada articuloEntrada;
     private Salida salida;
     private UnidadDeMedida unidadDeMedida;
     private BigDecimal cantidadPieza;
     private BigDecimal cantidadPaquete;
     private BigDecimal cantidadCaja;
     private String esResguardo;
     private String numSerie;
     private String observaciones;
     private Date fechaReg;

    public ArticuloSalida() {
    }

	
    public ArticuloSalida(Acceso acceso, ArticuloEntrada articuloEntrada, Salida salida, UnidadDeMedida unidadDeMedida, BigDecimal cantidadPieza, BigDecimal cantidadPaquete, BigDecimal cantidadCaja, Date fechaReg) {
        this.acceso = acceso;
        this.articuloEntrada = articuloEntrada;
        this.salida = salida;
        this.unidadDeMedida = unidadDeMedida;
        this.cantidadPieza = cantidadPieza;
        this.cantidadPaquete = cantidadPaquete;
        this.cantidadCaja = cantidadCaja;
        this.fechaReg = fechaReg;
    }
    public ArticuloSalida(Acceso acceso, ArticuloEntrada articuloEntrada, Salida salida, UnidadDeMedida unidadDeMedida, BigDecimal cantidadPieza, BigDecimal cantidadPaquete, BigDecimal cantidadCaja, String esResguardo, String numSerie, String observaciones, Date fechaReg) {
       this.acceso = acceso;
       this.articuloEntrada = articuloEntrada;
       this.salida = salida;
       this.unidadDeMedida = unidadDeMedida;
       this.cantidadPieza = cantidadPieza;
       this.cantidadPaquete = cantidadPaquete;
       this.cantidadCaja = cantidadCaja;
       this.esResguardo = esResguardo;
       this.numSerie = numSerie;
       this.observaciones = observaciones;
       this.fechaReg = fechaReg;
    }
   
    public Integer getIdArticuloSalida() {
        return this.idArticuloSalida;
    }
    
    public void setIdArticuloSalida(Integer idArticuloSalida) {
        this.idArticuloSalida = idArticuloSalida;
    }
    public Acceso getAcceso() {
        return this.acceso;
    }
    
    public void setAcceso(Acceso acceso) {
        this.acceso = acceso;
    }
    public ArticuloEntrada getArticuloEntrada() {
        return this.articuloEntrada;
    }
    
    public void setArticuloEntrada(ArticuloEntrada articuloEntrada) {
        this.articuloEntrada = articuloEntrada;
    }
    public Salida getSalida() {
        return this.salida;
    }
    
    public void setSalida(Salida salida) {
        this.salida = salida;
    }
    public UnidadDeMedida getUnidadDeMedida() {
        return this.unidadDeMedida;
    }
    
    public void setUnidadDeMedida(UnidadDeMedida unidadDeMedida) {
        this.unidadDeMedida = unidadDeMedida;
    }
    public BigDecimal getCantidadPieza() {
        return this.cantidadPieza;
    }
    
    public void setCantidadPieza(BigDecimal cantidadPieza) {
        this.cantidadPieza = cantidadPieza;
    }
    public BigDecimal getCantidadPaquete() {
        return this.cantidadPaquete;
    }
    
    public void setCantidadPaquete(BigDecimal cantidadPaquete) {
        this.cantidadPaquete = cantidadPaquete;
    }
    public BigDecimal getCantidadCaja() {
        return this.cantidadCaja;
    }
    
    public void setCantidadCaja(BigDecimal cantidadCaja) {
        this.cantidadCaja = cantidadCaja;
    }
    public String getEsResguardo() {
        return this.esResguardo;
    }
    
    public void setEsResguardo(String esResguardo) {
        this.esResguardo = esResguardo;
    }
    public String getNumSerie() {
        return this.numSerie;
    }
    
    public void setNumSerie(String numSerie) {
        this.numSerie = numSerie;
    }
    public String getObservaciones() {
        return this.observaciones;
    }
    
    public void setObservaciones(String observaciones) {
        this.observaciones = observaciones;
    }
    public Date getFechaReg() {
        return this.fechaReg;
    }
    
    public void setFechaReg(Date fechaReg) {
        this.fechaReg = fechaReg;
    }




}


