package com.almacen.model;
// Generated 29/06/2016 01:34:56 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Departamento generated by hbm2java
 */
public class Departamento  implements java.io.Serializable {


     private Integer idDepartamento;
     private Acceso acceso;
     private Byte idNivelDepartamento;
     private String departamento;
     private String cct;
     private String direccion;
     private String municipio;
     private String clave;
     private String descripcion;
     private String vigente;
     private Byte idDeptoPadre;
     private Date fechaReg;
     private Set<Factura> facturas = new HashSet<Factura>(0);
     private Set<ArticuloEntrada> articuloEntradas = new HashSet<ArticuloEntrada>(0);
     private Set<Salida> salidas = new HashSet<Salida>(0);
     private Set<Empleado> empleados = new HashSet<Empleado>(0);

    public Departamento() {
    }

	
    public Departamento(Acceso acceso, String departamento, String clave, String vigente, Date fechaReg) {
        this.acceso = acceso;
        this.departamento = departamento;
        this.clave = clave;
        this.vigente = vigente;
        this.fechaReg = fechaReg;
    }
    public Departamento(Acceso acceso, Byte idNivelDepartamento, String departamento, String cct, String direccion, String municipio, String clave, String descripcion, String vigente, Byte idDeptoPadre, Date fechaReg, Set<Factura> facturas, Set<ArticuloEntrada> articuloEntradas, Set<Salida> salidas, Set<Empleado> empleados) {
       this.acceso = acceso;
       this.idNivelDepartamento = idNivelDepartamento;
       this.departamento = departamento;
       this.cct = cct;
       this.direccion = direccion;
       this.municipio = municipio;
       this.clave = clave;
       this.descripcion = descripcion;
       this.vigente = vigente;
       this.idDeptoPadre = idDeptoPadre;
       this.fechaReg = fechaReg;
       this.facturas = facturas;
       this.articuloEntradas = articuloEntradas;
       this.salidas = salidas;
       this.empleados = empleados;
    }
   
    public Integer getIdDepartamento() {
        return this.idDepartamento;
    }
    
    public void setIdDepartamento(Integer idDepartamento) {
        this.idDepartamento = idDepartamento;
    }
    public Acceso getAcceso() {
        return this.acceso;
    }
    
    public void setAcceso(Acceso acceso) {
        this.acceso = acceso;
    }
    public Byte getIdNivelDepartamento() {
        return this.idNivelDepartamento;
    }
    
    public void setIdNivelDepartamento(Byte idNivelDepartamento) {
        this.idNivelDepartamento = idNivelDepartamento;
    }
    public String getDepartamento() {
        return this.departamento;
    }
    
    public void setDepartamento(String departamento) {
        this.departamento = departamento;
    }
    public String getCct() {
        return this.cct;
    }
    
    public void setCct(String cct) {
        this.cct = cct;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getMunicipio() {
        return this.municipio;
    }
    
    public void setMunicipio(String municipio) {
        this.municipio = municipio;
    }
    public String getClave() {
        return this.clave;
    }
    
    public void setClave(String clave) {
        this.clave = clave;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getVigente() {
        return this.vigente;
    }
    
    public void setVigente(String vigente) {
        this.vigente = vigente;
    }
    public Byte getIdDeptoPadre() {
        return this.idDeptoPadre;
    }
    
    public void setIdDeptoPadre(Byte idDeptoPadre) {
        this.idDeptoPadre = idDeptoPadre;
    }
    public Date getFechaReg() {
        return this.fechaReg;
    }
    
    public void setFechaReg(Date fechaReg) {
        this.fechaReg = fechaReg;
    }
    public Set<Factura> getFacturas() {
        return this.facturas;
    }
    
    public void setFacturas(Set<Factura> facturas) {
        this.facturas = facturas;
    }
    public Set<ArticuloEntrada> getArticuloEntradas() {
        return this.articuloEntradas;
    }
    
    public void setArticuloEntradas(Set<ArticuloEntrada> articuloEntradas) {
        this.articuloEntradas = articuloEntradas;
    }
    public Set<Salida> getSalidas() {
        return this.salidas;
    }
    
    public void setSalidas(Set<Salida> salidas) {
        this.salidas = salidas;
    }
    public Set<Empleado> getEmpleados() {
        return this.empleados;
    }
    
    public void setEmpleados(Set<Empleado> empleados) {
        this.empleados = empleados;
    }




}


