package com.almacen.model;
// Generated 29/06/2016 01:34:56 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Empleado generated by hbm2java
 */
public class Empleado  implements java.io.Serializable {


     private Integer idEmpleado;
     private Acceso acceso;
     private Departamento departamento;
     private String nombre;
     private String app;
     private String apm;
     private String email;
     private String telefono;
     private String celular;
     private String rfc;
     private String curp;
     private Date fechaNacimiento;
     private String direccion;
     private String puesto;
     private String foto;
     private String clave;
     private String vigente;
     private Date fechaReg;
     private Set<Salida> salidas = new HashSet<Salida>(0);

    public Empleado() {
    }

	
    public Empleado(Acceso acceso, Departamento departamento, String nombre, String app, String rfc, String curp, Date fechaNacimiento, String clave, Date fechaReg) {
        this.acceso = acceso;
        this.departamento = departamento;
        this.nombre = nombre;
        this.app = app;
        this.rfc = rfc;
        this.curp = curp;
        this.fechaNacimiento = fechaNacimiento;
        this.clave = clave;
        this.fechaReg = fechaReg;
    }
    public Empleado(Acceso acceso, Departamento departamento, String nombre, String app, String apm, String email, String telefono, String celular, String rfc, String curp, Date fechaNacimiento, String direccion, String puesto, String foto, String clave, String vigente, Date fechaReg, Set<Salida> salidas) {
       this.acceso = acceso;
       this.departamento = departamento;
       this.nombre = nombre;
       this.app = app;
       this.apm = apm;
       this.email = email;
       this.telefono = telefono;
       this.celular = celular;
       this.rfc = rfc;
       this.curp = curp;
       this.fechaNacimiento = fechaNacimiento;
       this.direccion = direccion;
       this.puesto = puesto;
       this.foto = foto;
       this.clave = clave;
       this.vigente = vigente;
       this.fechaReg = fechaReg;
       this.salidas = salidas;
    }
   
    public Integer getIdEmpleado() {
        return this.idEmpleado;
    }
    
    public void setIdEmpleado(Integer idEmpleado) {
        this.idEmpleado = idEmpleado;
    }
    public Acceso getAcceso() {
        return this.acceso;
    }
    
    public void setAcceso(Acceso acceso) {
        this.acceso = acceso;
    }
    public Departamento getDepartamento() {
        return this.departamento;
    }
    
    public void setDepartamento(Departamento departamento) {
        this.departamento = departamento;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApp() {
        return this.app;
    }
    
    public void setApp(String app) {
        this.app = app;
    }
    public String getApm() {
        return this.apm;
    }
    
    public void setApm(String apm) {
        this.apm = apm;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public String getCelular() {
        return this.celular;
    }
    
    public void setCelular(String celular) {
        this.celular = celular;
    }
    public String getRfc() {
        return this.rfc;
    }
    
    public void setRfc(String rfc) {
        this.rfc = rfc;
    }
    public String getCurp() {
        return this.curp;
    }
    
    public void setCurp(String curp) {
        this.curp = curp;
    }
    public Date getFechaNacimiento() {
        return this.fechaNacimiento;
    }
    
    public void setFechaNacimiento(Date fechaNacimiento) {
        this.fechaNacimiento = fechaNacimiento;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getPuesto() {
        return this.puesto;
    }
    
    public void setPuesto(String puesto) {
        this.puesto = puesto;
    }
    public String getFoto() {
        return this.foto;
    }
    
    public void setFoto(String foto) {
        this.foto = foto;
    }
    public String getClave() {
        return this.clave;
    }
    
    public void setClave(String clave) {
        this.clave = clave;
    }
    public String getVigente() {
        return this.vigente;
    }
    
    public void setVigente(String vigente) {
        this.vigente = vigente;
    }
    public Date getFechaReg() {
        return this.fechaReg;
    }
    
    public void setFechaReg(Date fechaReg) {
        this.fechaReg = fechaReg;
    }
    public Set<Salida> getSalidas() {
        return this.salidas;
    }
    
    public void setSalidas(Set<Salida> salidas) {
        this.salidas = salidas;
    }




}


