package com.almacen.model;
// Generated 29/06/2016 01:34:56 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Factura generated by hbm2java
 */
public class Factura  implements java.io.Serializable {


     private Integer idFactura;
     private Acceso acceso;
     private Departamento departamento;
     private FormaDePago formaDePago;
     private Proveedor proveedor;
     private TipoEntrada tipoEntrada;
     private String folioRequisicion;
     private int folioInterno;
     private String folioFactura;
     private Date fechaFactura;
     private Date fechaRecepcion;
     private BigDecimal importeFactura;
     private String descripcion;
     private String instruccion;
     private String foto;
     private String vigente;
     private Date fechaReg;
     private Set<ArticuloEntrada> articuloEntradas = new HashSet<ArticuloEntrada>(0);

    public Factura() {
    }

	
    public Factura(Acceso acceso, Departamento departamento, FormaDePago formaDePago, Proveedor proveedor, TipoEntrada tipoEntrada, int folioInterno, String folioFactura, Date fechaFactura, Date fechaRecepcion, BigDecimal importeFactura, Date fechaReg) {
        this.acceso = acceso;
        this.departamento = departamento;
        this.formaDePago = formaDePago;
        this.proveedor = proveedor;
        this.tipoEntrada = tipoEntrada;
        this.folioInterno = folioInterno;
        this.folioFactura = folioFactura;
        this.fechaFactura = fechaFactura;
        this.fechaRecepcion = fechaRecepcion;
        this.importeFactura = importeFactura;
        this.fechaReg = fechaReg;
    }
    public Factura(Acceso acceso, Departamento departamento, FormaDePago formaDePago, Proveedor proveedor, TipoEntrada tipoEntrada, String folioRequisicion, int folioInterno, String folioFactura, Date fechaFactura, Date fechaRecepcion, BigDecimal importeFactura, String descripcion, String instruccion, String foto, String vigente, Date fechaReg, Set<ArticuloEntrada> articuloEntradas) {
       this.acceso = acceso;
       this.departamento = departamento;
       this.formaDePago = formaDePago;
       this.proveedor = proveedor;
       this.tipoEntrada = tipoEntrada;
       this.folioRequisicion = folioRequisicion;
       this.folioInterno = folioInterno;
       this.folioFactura = folioFactura;
       this.fechaFactura = fechaFactura;
       this.fechaRecepcion = fechaRecepcion;
       this.importeFactura = importeFactura;
       this.descripcion = descripcion;
       this.instruccion = instruccion;
       this.foto = foto;
       this.vigente = vigente;
       this.fechaReg = fechaReg;
       this.articuloEntradas = articuloEntradas;
    }
   
    public Integer getIdFactura() {
        return this.idFactura;
    }
    
    public void setIdFactura(Integer idFactura) {
        this.idFactura = idFactura;
    }
    public Acceso getAcceso() {
        return this.acceso;
    }
    
    public void setAcceso(Acceso acceso) {
        this.acceso = acceso;
    }
    public Departamento getDepartamento() {
        return this.departamento;
    }
    
    public void setDepartamento(Departamento departamento) {
        this.departamento = departamento;
    }
    public FormaDePago getFormaDePago() {
        return this.formaDePago;
    }
    
    public void setFormaDePago(FormaDePago formaDePago) {
        this.formaDePago = formaDePago;
    }
    public Proveedor getProveedor() {
        return this.proveedor;
    }
    
    public void setProveedor(Proveedor proveedor) {
        this.proveedor = proveedor;
    }
    public TipoEntrada getTipoEntrada() {
        return this.tipoEntrada;
    }
    
    public void setTipoEntrada(TipoEntrada tipoEntrada) {
        this.tipoEntrada = tipoEntrada;
    }
    public String getFolioRequisicion() {
        return this.folioRequisicion;
    }
    
    public void setFolioRequisicion(String folioRequisicion) {
        this.folioRequisicion = folioRequisicion;
    }
    public int getFolioInterno() {
        return this.folioInterno;
    }
    
    public void setFolioInterno(int folioInterno) {
        this.folioInterno = folioInterno;
    }
    public String getFolioFactura() {
        return this.folioFactura;
    }
    
    public void setFolioFactura(String folioFactura) {
        this.folioFactura = folioFactura;
    }
    public Date getFechaFactura() {
        return this.fechaFactura;
    }
    
    public void setFechaFactura(Date fechaFactura) {
        this.fechaFactura = fechaFactura;
    }
    public Date getFechaRecepcion() {
        return this.fechaRecepcion;
    }
    
    public void setFechaRecepcion(Date fechaRecepcion) {
        this.fechaRecepcion = fechaRecepcion;
    }
    public BigDecimal getImporteFactura() {
        return this.importeFactura;
    }
    
    public void setImporteFactura(BigDecimal importeFactura) {
        this.importeFactura = importeFactura;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getInstruccion() {
        return this.instruccion;
    }
    
    public void setInstruccion(String instruccion) {
        this.instruccion = instruccion;
    }
    public String getFoto() {
        return this.foto;
    }
    
    public void setFoto(String foto) {
        this.foto = foto;
    }
    public String getVigente() {
        return this.vigente;
    }
    
    public void setVigente(String vigente) {
        this.vigente = vigente;
    }
    public Date getFechaReg() {
        return this.fechaReg;
    }
    
    public void setFechaReg(Date fechaReg) {
        this.fechaReg = fechaReg;
    }
    public Set<ArticuloEntrada> getArticuloEntradas() {
        return this.articuloEntradas;
    }
    
    public void setArticuloEntradas(Set<ArticuloEntrada> articuloEntradas) {
        this.articuloEntradas = articuloEntradas;
    }




}


