package com.almacen.model;
// Generated 27/06/2016 04:27:58 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Marca generated by hbm2java
 */
public class Marca  implements java.io.Serializable {


     private Integer idMarca;
     private Acceso acceso;
     private String marca;
     private String vigente;
     private Date fechareg;
     private Set<Articulo> articulos = new HashSet<Articulo>(0);

    public Marca() {
    }

	
    public Marca(Acceso acceso, String marca, Date fechareg) {
        this.acceso = acceso;
        this.marca = marca;
        this.fechareg = fechareg;
    }
    public Marca(Acceso acceso, String marca, String vigente, Date fechareg, Set<Articulo> articulos) {
       this.acceso = acceso;
       this.marca = marca;
       this.vigente = vigente;
       this.fechareg = fechareg;
       this.articulos = articulos;
    }
   
    public Integer getIdMarca() {
        return this.idMarca;
    }
    
    public void setIdMarca(Integer idMarca) {
        this.idMarca = idMarca;
    }
    public Acceso getAcceso() {
        return this.acceso;
    }
    
    public void setAcceso(Acceso acceso) {
        this.acceso = acceso;
    }
    public String getMarca() {
        return this.marca;
    }
    
    public void setMarca(String marca) {
        this.marca = marca;
    }
    public String getVigente() {
        return this.vigente;
    }
    
    public void setVigente(String vigente) {
        this.vigente = vigente;
    }
    public Date getFechareg() {
        return this.fechareg;
    }
    
    public void setFechareg(Date fechareg) {
        this.fechareg = fechareg;
    }
    public Set<Articulo> getArticulos() {
        return this.articulos;
    }
    
    public void setArticulos(Set<Articulo> articulos) {
        this.articulos = articulos;
    }




}


