package com.almacen.model;
// Generated 27/06/2016 04:27:58 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Proveedor generated by hbm2java
 */
public class Proveedor  implements java.io.Serializable {


     private Integer idProveedor;
     private Acceso acceso;
     private String proveedor;
     private String rfc;
     private String direccion;
     private String telefono;
     private String correo;
     private String paginaWeb;
     private String contacto;
     private String observaciones;
     private String vigente;
     private Date fechareg;
     private Set<Factura> facturas = new HashSet<Factura>(0);

    public Proveedor() {
    }

	
    public Proveedor(Acceso acceso, String proveedor, String rfc, String direccion, String telefono, String contacto, String vigente, Date fechareg) {
        this.acceso = acceso;
        this.proveedor = proveedor;
        this.rfc = rfc;
        this.direccion = direccion;
        this.telefono = telefono;
        this.contacto = contacto;
        this.vigente = vigente;
        this.fechareg = fechareg;
    }
    public Proveedor(Acceso acceso, String proveedor, String rfc, String direccion, String telefono, String correo, String paginaWeb, String contacto, String observaciones, String vigente, Date fechareg, Set<Factura> facturas) {
       this.acceso = acceso;
       this.proveedor = proveedor;
       this.rfc = rfc;
       this.direccion = direccion;
       this.telefono = telefono;
       this.correo = correo;
       this.paginaWeb = paginaWeb;
       this.contacto = contacto;
       this.observaciones = observaciones;
       this.vigente = vigente;
       this.fechareg = fechareg;
       this.facturas = facturas;
    }
   
    public Integer getIdProveedor() {
        return this.idProveedor;
    }
    
    public void setIdProveedor(Integer idProveedor) {
        this.idProveedor = idProveedor;
    }
    public Acceso getAcceso() {
        return this.acceso;
    }
    
    public void setAcceso(Acceso acceso) {
        this.acceso = acceso;
    }
    public String getProveedor() {
        return this.proveedor;
    }
    
    public void setProveedor(String proveedor) {
        this.proveedor = proveedor;
    }
    public String getRfc() {
        return this.rfc;
    }
    
    public void setRfc(String rfc) {
        this.rfc = rfc;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public String getCorreo() {
        return this.correo;
    }
    
    public void setCorreo(String correo) {
        this.correo = correo;
    }
    public String getPaginaWeb() {
        return this.paginaWeb;
    }
    
    public void setPaginaWeb(String paginaWeb) {
        this.paginaWeb = paginaWeb;
    }
    public String getContacto() {
        return this.contacto;
    }
    
    public void setContacto(String contacto) {
        this.contacto = contacto;
    }
    public String getObservaciones() {
        return this.observaciones;
    }
    
    public void setObservaciones(String observaciones) {
        this.observaciones = observaciones;
    }
    public String getVigente() {
        return this.vigente;
    }
    
    public void setVigente(String vigente) {
        this.vigente = vigente;
    }
    public Date getFechareg() {
        return this.fechareg;
    }
    
    public void setFechareg(Date fechareg) {
        this.fechareg = fechareg;
    }
    public Set<Factura> getFacturas() {
        return this.facturas;
    }
    
    public void setFacturas(Set<Factura> facturas) {
        this.facturas = facturas;
    }




}


