package com.almacen.model;
// Generated 27/06/2016 04:27:58 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * SubCatalogoBienes generated by hbm2java
 */
public class SubCatalogoBienes  implements java.io.Serializable {


     private Integer idSubCatalogoBienes;
     private Acceso acceso;
     private CatalogoBienes catalogoBienes;
     private String subCatalogo;
     private String clave;
     private String descripcion;
     private String vigente;
     private Date fechaReg;
     private Set<Articulo> articulos = new HashSet<Articulo>(0);

    public SubCatalogoBienes() {
    }

	
    public SubCatalogoBienes(Acceso acceso, CatalogoBienes catalogoBienes, String subCatalogo, String clave, String vigente, Date fechaReg) {
        this.acceso = acceso;
        this.catalogoBienes = catalogoBienes;
        this.subCatalogo = subCatalogo;
        this.clave = clave;
        this.vigente = vigente;
        this.fechaReg = fechaReg;
    }
    public SubCatalogoBienes(Acceso acceso, CatalogoBienes catalogoBienes, String subCatalogo, String clave, String descripcion, String vigente, Date fechaReg, Set<Articulo> articulos) {
       this.acceso = acceso;
       this.catalogoBienes = catalogoBienes;
       this.subCatalogo = subCatalogo;
       this.clave = clave;
       this.descripcion = descripcion;
       this.vigente = vigente;
       this.fechaReg = fechaReg;
       this.articulos = articulos;
    }
   
    public Integer getIdSubCatalogoBienes() {
        return this.idSubCatalogoBienes;
    }
    
    public void setIdSubCatalogoBienes(Integer idSubCatalogoBienes) {
        this.idSubCatalogoBienes = idSubCatalogoBienes;
    }
    public Acceso getAcceso() {
        return this.acceso;
    }
    
    public void setAcceso(Acceso acceso) {
        this.acceso = acceso;
    }
    public CatalogoBienes getCatalogoBienes() {
        return this.catalogoBienes;
    }
    
    public void setCatalogoBienes(CatalogoBienes catalogoBienes) {
        this.catalogoBienes = catalogoBienes;
    }
    public String getSubCatalogo() {
        return this.subCatalogo;
    }
    
    public void setSubCatalogo(String subCatalogo) {
        this.subCatalogo = subCatalogo;
    }
    public String getClave() {
        return this.clave;
    }
    
    public void setClave(String clave) {
        this.clave = clave;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getVigente() {
        return this.vigente;
    }
    
    public void setVigente(String vigente) {
        this.vigente = vigente;
    }
    public Date getFechaReg() {
        return this.fechaReg;
    }
    
    public void setFechaReg(Date fechaReg) {
        this.fechaReg = fechaReg;
    }
    public Set<Articulo> getArticulos() {
        return this.articulos;
    }
    
    public void setArticulos(Set<Articulo> articulos) {
        this.articulos = articulos;
    }




}


