package com.almacen.model;
// Generated 27/06/2016 04:27:58 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TipoEntrada generated by hbm2java
 */
public class TipoEntrada  implements java.io.Serializable {


     private Integer idTipoEntrada;
     private Acceso acceso;
     private String tipoEntrada;
     private String descripcion;
     private String vigente;
     private Date fechaReg;
     private Set<Factura> facturas = new HashSet<Factura>(0);

    public TipoEntrada() {
    }

	
    public TipoEntrada(Acceso acceso, String tipoEntrada) {
        this.acceso = acceso;
        this.tipoEntrada = tipoEntrada;
    }
    public TipoEntrada(Acceso acceso, String tipoEntrada, String descripcion, String vigente, Date fechaReg, Set<Factura> facturas) {
       this.acceso = acceso;
       this.tipoEntrada = tipoEntrada;
       this.descripcion = descripcion;
       this.vigente = vigente;
       this.fechaReg = fechaReg;
       this.facturas = facturas;
    }
   
    public Integer getIdTipoEntrada() {
        return this.idTipoEntrada;
    }
    
    public void setIdTipoEntrada(Integer idTipoEntrada) {
        this.idTipoEntrada = idTipoEntrada;
    }
    public Acceso getAcceso() {
        return this.acceso;
    }
    
    public void setAcceso(Acceso acceso) {
        this.acceso = acceso;
    }
    public String getTipoEntrada() {
        return this.tipoEntrada;
    }
    
    public void setTipoEntrada(String tipoEntrada) {
        this.tipoEntrada = tipoEntrada;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getVigente() {
        return this.vigente;
    }
    
    public void setVigente(String vigente) {
        this.vigente = vigente;
    }
    public Date getFechaReg() {
        return this.fechaReg;
    }
    
    public void setFechaReg(Date fechaReg) {
        this.fechaReg = fechaReg;
    }
    public Set<Factura> getFacturas() {
        return this.facturas;
    }
    
    public void setFacturas(Set<Factura> facturas) {
        this.facturas = facturas;
    }




}


