package com.almacen.model;
// Generated 29/06/2016 01:34:56 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * UnidadDeMedida generated by hbm2java
 */
public class UnidadDeMedida  implements java.io.Serializable {


     private Integer idUnidadDeMedida;
     private String unidadDeMedida;
     private Set<ArticuloSalida> articuloSalidas = new HashSet<ArticuloSalida>(0);
     private Set<ArticuloEntrada> articuloEntradas = new HashSet<ArticuloEntrada>(0);

    public UnidadDeMedida() {
    }

	
    public UnidadDeMedida(String unidadDeMedida) {
        this.unidadDeMedida = unidadDeMedida;
    }
    public UnidadDeMedida(String unidadDeMedida, Set<ArticuloSalida> articuloSalidas, Set<ArticuloEntrada> articuloEntradas) {
       this.unidadDeMedida = unidadDeMedida;
       this.articuloSalidas = articuloSalidas;
       this.articuloEntradas = articuloEntradas;
    }
   
    public Integer getIdUnidadDeMedida() {
        return this.idUnidadDeMedida;
    }
    
    public void setIdUnidadDeMedida(Integer idUnidadDeMedida) {
        this.idUnidadDeMedida = idUnidadDeMedida;
    }
    public String getUnidadDeMedida() {
        return this.unidadDeMedida;
    }
    
    public void setUnidadDeMedida(String unidadDeMedida) {
        this.unidadDeMedida = unidadDeMedida;
    }
    public Set<ArticuloSalida> getArticuloSalidas() {
        return this.articuloSalidas;
    }
    
    public void setArticuloSalidas(Set<ArticuloSalida> articuloSalidas) {
        this.articuloSalidas = articuloSalidas;
    }
    public Set<ArticuloEntrada> getArticuloEntradas() {
        return this.articuloEntradas;
    }
    
    public void setArticuloEntradas(Set<ArticuloEntrada> articuloEntradas) {
        this.articuloEntradas = articuloEntradas;
    }




}


