package com.almacen.model;
// Generated 29/06/2016 01:34:56 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * UsuarioNivel generated by hbm2java
 */
public class UsuarioNivel  implements java.io.Serializable {


     private Integer idUsuarioNivel;
     private String usuarioNivel;
     private Set<Usuario> usuarios = new HashSet<Usuario>(0);

    public UsuarioNivel() {
    }

	
    public UsuarioNivel(String usuarioNivel) {
        this.usuarioNivel = usuarioNivel;
    }
    public UsuarioNivel(String usuarioNivel, Set<Usuario> usuarios) {
       this.usuarioNivel = usuarioNivel;
       this.usuarios = usuarios;
    }
   
    public Integer getIdUsuarioNivel() {
        return this.idUsuarioNivel;
    }
    
    public void setIdUsuarioNivel(Integer idUsuarioNivel) {
        this.idUsuarioNivel = idUsuarioNivel;
    }
    public String getUsuarioNivel() {
        return this.usuarioNivel;
    }
    
    public void setUsuarioNivel(String usuarioNivel) {
        this.usuarioNivel = usuarioNivel;
    }
    public Set<Usuario> getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set<Usuario> usuarios) {
        this.usuarios = usuarios;
    }




}


