package com.almacen.model;
// Generated 27/06/2016 04:27:58 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private Integer idUsuario;
     private UsuarioNivel usuarioNivel;
     private UsuarioStatus usuarioStatus;
     private String nombre;
     private String usuario;
     private String passwd;
     private Date fechaReg;
     private Set<Acceso> accesos = new HashSet<Acceso>(0);
     private Set<UsuarioPermiso> usuarioPermisos = new HashSet<UsuarioPermiso>(0);

    public Usuario() {
    }

	
    public Usuario(UsuarioNivel usuarioNivel, UsuarioStatus usuarioStatus, String nombre, String usuario, String passwd, Date fechaReg) {
        this.usuarioNivel = usuarioNivel;
        this.usuarioStatus = usuarioStatus;
        this.nombre = nombre;
        this.usuario = usuario;
        this.passwd = passwd;
        this.fechaReg = fechaReg;
    }
    public Usuario(UsuarioNivel usuarioNivel, UsuarioStatus usuarioStatus, String nombre, String usuario, String passwd, Date fechaReg, Set<Acceso> accesos, Set<UsuarioPermiso> usuarioPermisos) {
       this.usuarioNivel = usuarioNivel;
       this.usuarioStatus = usuarioStatus;
       this.nombre = nombre;
       this.usuario = usuario;
       this.passwd = passwd;
       this.fechaReg = fechaReg;
       this.accesos = accesos;
       this.usuarioPermisos = usuarioPermisos;
    }
   
    public Integer getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(Integer idUsuario) {
        this.idUsuario = idUsuario;
    }
    public UsuarioNivel getUsuarioNivel() {
        return this.usuarioNivel;
    }
    
    public void setUsuarioNivel(UsuarioNivel usuarioNivel) {
        this.usuarioNivel = usuarioNivel;
    }
    public UsuarioStatus getUsuarioStatus() {
        return this.usuarioStatus;
    }
    
    public void setUsuarioStatus(UsuarioStatus usuarioStatus) {
        this.usuarioStatus = usuarioStatus;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }
    public String getPasswd() {
        return this.passwd;
    }
    
    public void setPasswd(String passwd) {
        this.passwd = passwd;
    }
    public Date getFechaReg() {
        return this.fechaReg;
    }
    
    public void setFechaReg(Date fechaReg) {
        this.fechaReg = fechaReg;
    }
    public Set<Acceso> getAccesos() {
        return this.accesos;
    }
    
    public void setAccesos(Set<Acceso> accesos) {
        this.accesos = accesos;
    }
    public Set<UsuarioPermiso> getUsuarioPermisos() {
        return this.usuarioPermisos;
    }
    
    public void setUsuarioPermisos(Set<UsuarioPermiso> usuarioPermisos) {
        this.usuarioPermisos = usuarioPermisos;
    }




}


